# Generated by Django 2.1.7 on 2019-04-02 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_num', models.IntegerField()),
                ('id_num', models.IntegerField()),
                ('pname', models.CharField(max_length=300)),
                ('_class', models.CharField(max_length=300)),
                ('des', models.TextField()),
                ('owner', models.CharField(max_length=300)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_num', models.IntegerField()),
                ('id_num', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('benefit', models.TextField()),
                ('e_start_date', models.DateField()),
                ('e_close_date', models.DateField()),
                ('a_start_date', models.DateField()),
                ('a_close_date', models.DateField()),
                ('leader', models.CharField(max_length=300)),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.Project')),
            ],
        ),
        migrations.CreateModel(
            name='SubProjectAppriasal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_num', models.IntegerField()),
                ('id_num', models.IntegerField()),
                ('sid_num', models.IntegerField()),
                ('ap_date', models.DateField()),
                ('delay_reason', models.TextField()),
                ('r_action', models.TextField()),
                ('a_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SubProjectCloseout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_num', models.IntegerField()),
                ('id_num', models.IntegerField()),
                ('sid_num', models.IntegerField()),
                ('close_num', models.IntegerField()),
                ('c_date', models.DateField()),
                ('remark', models.TextField()),
                ('a_name', models.CharField(max_length=300)),
            ],
        ),
    ]
