# Generated by Django 2.1.7 on 2019-04-03 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_funder', models.CharField(max_length=300)),
                ('nature_funding', models.TextField()),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=300)),
            ],
        ),
        migrations.RenameField(
            model_name='subproject',
            old_name='code_num',
            new_name='scode_num',
        ),
        migrations.RenameField(
            model_name='subproject',
            old_name='id_num',
            new_name='sid_num',
        ),
        migrations.RemoveField(
            model_name='subprojectappriasal',
            name='code_num',
        ),
        migrations.RemoveField(
            model_name='subprojectappriasal',
            name='id_num',
        ),
        migrations.RemoveField(
            model_name='subprojectappriasal',
            name='sid_num',
        ),
        migrations.RemoveField(
            model_name='subprojectcloseout',
            name='code_num',
        ),
        migrations.AddField(
            model_name='subproject',
            name='id_num_beneficiary',
            field=models.CharField(default='no id', max_length=300),
        ),
        migrations.AddField(
            model_name='subproject',
            name='spname',
            field=models.CharField(default='no name', max_length=300),
        ),
        migrations.AddField(
            model_name='subprojectappriasal',
            name='owned_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myproject.SubProject'),
        ),
        migrations.AddField(
            model_name='subprojectcloseout',
            name='owned_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myproject.SubProject'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='pname',
            field=models.SlugField(max_length=300),
        ),
        migrations.AddField(
            model_name='projectfund',
            name='owned_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myproject.Project'),
        ),
    ]
