# Generated by Django 2.1.7 on 2019-04-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_auto_20190403_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='pname',
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='this-is-slug', max_length=300, unique=True, verbose_name='Project Name'),
        ),
    ]
